spring:
  config:
    import: configserver:http://localhost:8888
  r2dbc:
    password: 1234
    url: r2dbc:pool:mysql://localhost:3306/profiledb
    username: root
  application:
    name: profile-service
server:
  port: 9214